[tool.black]
line-length = 100
py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[tool.isort]
default_section = "THIRDPARTY"
include_trailing_comma = true
line_length = 100
multi_line_output = 3
use_parentheses = true
